### ISSUE TITLE
different results between julia 1.10 vs osx builtin

### ISSUE THREAD

**Issue by jonalm** [oxinabox/MD5.jl#16]
consider the following (on mac M2)

```
> echo "asdpfginpqvwen" >> foo
> md5 foo
MD5 (foo) = 610d6da0969779be0e9c6c1386218660
```

Now opening julia 1.10 and MD5 v0.2.2, I get
```
julia> using MD5
julia> bytes2hex(md5("foo"))
"acbd18db4cc2f85cedef654fccc4a4d8"
```

How come these results are different?

**Comment by BonelessPi** [comment]
In your first code block, you run the command `md5 foo` which reads the content of the _file_ "foo" and runs the MD5 hash of its contents. In addition, I believe the `echo` command also adds a newline character to the end of the input. On my machine the hash seems to match your expected output:
```
julia> bytes2hex(md5("asdpfginpqvwen\n"))
"610d6da0969779be0e9c6c1386218660"
```

In the second code block, you use julia to run the MD5 hash of the _string_ "foo". In order to run the hash on the contents, you would want something like:
```
open("foo") do f
     bytes2hex(md5(f))
end
```

**Comment by jonalm** [comment]
Many thanks @BonelessPi!
